# -*- coding: utf-8 -*-
{

    'name': "SOCHEPRESS BASE",
    'summary': """Sochepress base module""",
    'description': """Generic Module for the sochepress""",
    'author': "Assabe POLO, PYVAL",
    'website': "https://pyval.com/",
    'category': 'Uncategorized',
    'version': '13.0',
    'depends': ['base', 'account', 'fleet','base_geolocalize',
                'kzm_invoice_report', 'rating', 'report_xlsx', 'report_qr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/customer_request_sequence.xml',
        'data/contract_stage_data.xml',
        'data/mail_template.xml',
        'data/motif_data.xml',
        # 'data/motif_data2.xml',
        'data/res_partner_category.xml',
        'data/return_methods.xml',
        'data/payment_method_data.xml',
        'data/sochepress_expedition_declaration_sequence.xml',
        'data/sls_sms_type.xml',
        'data/seq.xml',
        'views/config_models_views.xml',
        'views/customer_request_views.xml',
        'views/form.xml',
        'views/sochepress_colis_delivery.xml',
        'views/sochepress_contract_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/price_list_view.xml',
        'views/account_move_views.xml',
        'views/accoun_payment.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/colis_views.xml',
        'views/transport_order_views.xml',
        'views/sls_return_method.xml',
        'views/sochepress_marchandise.xml',
        'views/res_config_setting.xml',
        'views/product_template_views.xml',
        'views/sochepress_expedition_dectaration.xml',
        'views/sochepress_code_otp_wizard.xml',
        'views/sochepress_document_colis_views.xml',
        'views/sochepress_document_type_views.xml',
        'views/rating_rating.xml',
        'views/sls_sms_type.xml',
        'views/delivery_timing_views.xml',
        'views/res_users_views.xml',
        'views/colis_return_wizard.xml',
        'views/sochepress_req_wizard.xml',
        'views/transport_verification_wizard.xml',
        'views/sochepress_justif_wizard.xml',
        'views/templates.xml',
        'views/menus.xml',
        'reports/invoice_report_view.xml',
        'reports/customer_report_view.xml',
        'reports/colis_barecodes_report.xml',
        'reports/colis_qrcodes_report.xml',
        'reports/transport_order_barecode.xml',
        'data/sequences.xml'
    ],
    'external_dependencies': {"python": ["pyotp", 'qrcode']},
}
